### ISSUE TITLE
定义一个插件模型

### ISSUE THREAD

**Issue by otakustay** [ecomfe/uioc#34]
让ioc的核心只保持模块的加载和插件的协调功能，将对象的加载和创建定义一个明确的分阶段生命周期，在各个阶段都可以应用插件，比如：

- 对象模块路径获取，可以指定自动化模块路径计算的插件，减小配置
- 对象的创建，构造函数注入作为插件实现
- 对象创建后，属性注入是一个插件，可以将`setXxx`和`set xxx`作为不同插件实现（可能工作比较复杂）

后续的AOP同样使用插件的模式实现，也存在使用多个阶段的插件，如`singleton`就是在对象创建阶段增加判断，并在对象创建后进行单例管理

**Comment by hardyguo** [comment]
Can say the detailed point？thank you!

**Comment by Exodia** [comment]
@see https://github.com/ecomfe/uioc/issues/42
