### ISSUE TITLE
es5 property getter 与 自动注入&属性注入冲突的问题

### ISSUE THREAD

**Issue by Exodia** [ecomfe/uioc#35]
在 property getter 中会存在逻辑去获取实例上的 ioc 依赖，但这个时候实例的依赖可能并没有注入完成，此时的依赖为 undefined，导致异常， 代码如下：

```javascript
ioc.addComponents({
     a: {
           module: 'a',
           auto: true
     },
    b: {
         creator: {
              fn() {}
         }, 
        scope: 'static'
    }
});

class A {
    constructor() {
         let a = this.a;
         // xxxx
    }
     get a () {
            let c = this.getB().fn();
     }
     setB(b) {
          this.b = b;
     }
    getB() {
         return this.b;
    }
}
```

另外：ioc/Setter.js下的 Setter#getPropertyFromSetter方法检测属性逻辑存在缺陷：
```javascript
Setter.prototype.getPropertyFromSetter = function (instance, name) {
     var prop = null;
      // 这行代码会导致 property getter 执行，具有一定的副作用
      if (typeof instance[name] === 'function' && SETTER_REGEX.test(name)) {
             prop = name.charAt(SET_LEGTH).toLowerCase() + name.slice(SET_LEGTH + 1);
       }

        return prop;
};
```

**Comment by otakustay** [comment]
构造函数执行时依赖未完成注入这个应该是常识才对……

**Comment by Exodia** [comment]
不小心没写完就发出去了- -。。。构造函数那块是这样，合理，下面的 setter 检测逻辑就是 ioc 的问题了

**Comment by Exodia** [comment]
setter 检测逻辑应该先校验正则，符合setter 规则，再从 descriptor 中拿 value或者 get(), 但还是无法避免 setter 从 property getter 生成的副作用，只能在很大程度上缓解， 使用者需要有一定约束：从 property getter 中生成的 ioc setter， 不能有需要 ioc 注入的依赖。

**Comment by otakustay** [comment]
这个我们应该有讨论过，应该用`getOwnPropertyDescriptor`去判断是否存在，而不是直接访问……

上面的例子我也没搞清楚，是因为`auto: true`所以会遍历所有的`setter`导致会访问`get a()`吗？

**Comment by Exodia** [comment]
getOwnPropertyDescriptor 这个流程在前面，负责拿到 property name，但现在是下一个流程的问题，需要根据 property name 获取 property，然后检测 property 是否为 function，必须得获取到 property value 才能判断，如果 property 为 get()的话就有问题了

**Comment by otakustay** [comment]
不是一个属性必须满足以下条件之一才认为需要注入吗？

1. 是一个`set()`
2. 命名为`setXxx`且为普通对象且类型为`function`

因此这个判断是不是应该为：

```js
descriptor.set
    || (
        SETTER_REGEX.test(name)
        && descriptor.hasOwnProperty('value')
        && typeof descriptor.value === 'function'
    )
```

**Comment by Exodia** [comment]
意思是下面的代码不符合 auto 规则？ 当然我目前暂时也打算这样干。
```javascript
class A {
     get setB() {
           return () => {};
     }
}
```

**Comment by otakustay** [comment]
不符合，过于边界的情况我想没必要去折腾，因为我们在`auto`之外也有显式配置的能力，真有这种情况就显式配置
