### ISSUE TITLE
支持类的高阶转换

### ISSUE THREAD

**Issue by otakustay** [ecomfe/uioc#41]
我希望ioc支持这样一个功能：

```js
{
    foo: {
        module: 'foo',
        scope: 'static'
    },
    bar: {
        module: 'bar',
        scope: 'static'
    },
    main: {
        module: 'common/Main',
        transformers: [
            {$ref: 'foo'},
            {$ref: 'bar'}
        ]
    }
}
```

此时如果`ioc.getComponent('main')`得到的是`new bar(foo(Main))()`

这能让我不用在每个框架中都支持基于高阶转换的extension实现，让ioc统一负责这一功能

**Comment by Exodia** [comment]
我的想法是单纯 ioc 框架核心不应该支持这种功能，这个功能让插件来做支持会更适合，后续插件功能完成后做个这样的插件支持下如何

**Comment by otakustay** [comment]
嗯，有插件机制的前提下通过插件来做更好

**Comment by Exodia** [comment]
will resolved by https://github.com/ecomfe/uioc/issues/42
