### ISSUE TITLE
IoC 插件机制

### ISSUE THREAD

**Issue by Exodia** [ecomfe/uioc#42]
## 当前的容器生命周期

1. 实例化容器

2. 注册组件

3. 获取组件 
    3.1 调用各个操作符解析当前组件配置，设置静态化的依赖
    3.2 根据组件配置加载所需模块
    3.3 创建实例
      - 3.3.1 根据组件配置获取构造函数依赖
      - 3.3.2 回到 3 获取构造函数依赖实例
      - 3.3.3 调用组件构造函数，传入构造函数依赖，创建组件实例
      - 3.3.4 回到 3 获取 property 依赖实例并注入
      - 3.3.5 根据实例获取 setter 依赖
      - 3.3.6 回到 3 获取setter 依赖实例并注入

4. 销毁容器    

#### string : get name()

钩子名称

#### <? exends IoCConfig> : onContainerInit(IoC : ioc, IoCConfig : config)  
容器实例化时调用，传入 ioc 容器和当前配置作为参数, 可以在此拦截容器级的配置，返回一个新的容器级配置提供给 ioc 使用, ioc将基于新的配置做后续操作。

场景：基于 ioc 的插件需要在容器级配置上获取必要的配置信息。

如： aop 插件需要从容器级别的配置上解析 aop 配置

#### <? extends ComponentConfig> : onAddComponent(IoC: ioc, string: componentId)

注册组件时调用，传入 ioc 容器，当前组件 id ，可以在此拦截组件级的配置，返回一个新的组件配置提供给 ioc 使用，ioc 将基于此配置做后续操作。

场景：插件需要在组件级的配置上获取必要的配置信息

如：语法糖插件可以针对组件配置做些静态的映射转换

#### <? extends ComponentConfig> : onGetComponent(IoC: ioc, string: componentId)

获取组件时调用，传入 ioc 容器，当前组件 id，可以在此拦截组件级的配置，返回一个新的组件配置提供给 ioc 使用，ioc 将基于此配置做后续操作。

场景：插件需要在组件级的配置上获取必要的配置信息，而某些信息需要在获取组件时才能方便的获得。

如：目前所有的依赖解析都在这个时机进行，因为此时所有的依赖组件信息最全。

#### Promise&lt;Any&gt; : beforeCreateInstance(IoC : ioc, string : id, Any : instance)

创建组件实例前调用，传入 ioc 容器，当前组件 id，和当前已经创建的实例(可能没有)，返回一个值为实例的 promise 给 ioc 使用，若返回值不为 promise，则不会覆盖现有实例， 若最终无实例，ioc 内部将根据组件配置创建实例，ioc 将基于此做后续操作。

场景：插件可以在此返回缓存实例，根据上下文信息做实例创建前的拦截操作。

如： 单例插件会在实例创建前检测是有缓存实例，有的话则返回。

#### Promise&lt;Any&gt; : afterCreateInstance(IoC : ioc, string : id, Any : instance)

创建组件实例后调用，传入 ioc 容器，当前组件 id，和当前已经创建的实例，返回一个值为实例的 promise 给 ioc 使用，若返回值不为 promise，则不会覆盖现有实例。

场景：插件可以在此缓存实例，根据上下文信息做实例创建后的操作。

如： 
- 单例插件会在此缓存实例。
- 自动注入插件会在此基于实例做自动注入
- 属性注入插件在此注入属性依赖

#### void : onContainerDispose(IoC: ioc)

销毁容器时调用。

场景：插件需要在容器销毁时释放资源。

如：缓存型/单例型插件需要在容器销毁时释放缓存资源。

## 容器插件

实现了 ILifeCircleHook 接口的子类

#### IoC#addPlugins(ILifeCircleHook[]: plugins, [, number : pos])

在容器指定位置上插入一系列插件实例，未传入指定位置时，追加到插件列表末尾。若插件名称已存在则抛出异常。

#### ILifeCircleHook[] : IoC#getPlugins()

返回容器当前的插件列表

#### ILifeCircleHook[] : IoCConfig.plugins

容器实例化时传入的插件配置项

## 多个插件实例在同个钩子函数上的执行顺序

 reduce 过程：FIFO，返回结果作为后续输入的一部分。

**Comment by otakustay** [comment]
首先在文档上插件的每个方法应该是个独立接口，而不是一个接口有这么多方法（学院派的意见）

其次，这个版本是否要考虑将property分成`setter`和`setMethod`分别处理？

然后，除了这个可以多个组件的插件外，我还希望有一些“扩展点”，区别于插件的是这些扩展点只能有一个实现，并不能多个组件起来：

1. 组件的scope管理（`static`、`transient`、`singleton`），即工作在`onCreateInstance`之前，产生实例的过程
2. Loader同样也可以是一类可配置的东西，现在已经有实现，但是不是可以更好地整合进整个体系中
3. 初始组件的配置解析，即工作在`onGetComponent`之前，产出`ComponentConfig`的过程

**Comment by Exodia** [comment]
> 首先在文档上插件的每个方法应该是个独立接口，而不是一个接口有这么多方法

这个我觉得都行，无非是一个插件要实现多个接口，还是一个插件要实现一个接口的多个方法的问题了。

但感觉体现给使用者要实现多个接口反而是一种记忆负担。

 > 是否要考虑将property分成setter和setMethod分别处理？

这块是指自动注入吗？暂时我还是想保留之前的方案，但有了插件机制，使用者可以很好的自己扩展自动注入的方式。

> “扩展点”

这里提到的1,2,3在 onContainerInit 这块应该就可以做了。

**Comment by otakustay** [comment]
> 这个我觉得都行，无非是一个插件要实现多个接口，还是一个插件要实现一个接口的多个方法的问题了。

因为设想我们实际使用中，会是一个插件只包含其中一个方法，并不会写其它方法，此时我们不能说“这个插件实现了`ILifeCircleHook`接口”，那么此时我们写出来的这个东西是什么呢？

所以每个方法是一个接口更容易声明

> 这块是指自动注入吗？暂时我还是想保留之前的方案，但有了插件机制，使用者可以很好的自己扩展自动注入的方式。

并非只是自动注入，“自动注入”和“自动判断属性是set还是setMethod”是两回事

> 这里提到的1,2,3在 onContainerInit 这块应该就可以做了。

不是很理解怎么做，比如我现在需要一个scope管理，叫“最多4个实例，轮着用”，在配置文件中体现为`scope: 'roundrobin'`，这个应该是针对每个组件配置的内容，在`onContainerInit`阶段如何处理

**Comment by Exodia** [comment]
> 每个方法是一个接口更容易声明

实际使用中是继承一个基础的 Plugin 基类，这里有默认实现，要不然实现不同接口的 plugin 非常不一致，虽然 js 的动态性可以在实现过程中用 if 去判断，但我更倾向 plugin 数组里都是统一的实现。

> 并非只是自动注入，“自动注入”和“自动判断属性是set还是setMethod”是两回事

这块我没有理解是什么意思？如果不是自动注入的话， property 本身好像没有太大问题？有 setMethod 就调用 setMothod，没的话就正常赋值。

> scope: 'roundrobin'

额，这块本来是想在 onCreateInstance 做的，现在来看这个没法做到，得增加一个创建实例前的声明周期，我稍后增加下。

> Loader同样也可以是一类可配置的东西，现在已经有实现，但是不是可以更好地整合进整个体系中

loader 这块暂时的想法就是按之前提供的 amd 接口，外部可以简单适配进来


> 初始组件的配置解析，即工作在onGetComponent之前，产出ComponentConfig的过程

onGetComponent会使用返回的组件配置进行后续操作，这块解决不了吗？

**Comment by otakustay** [comment]
> 虽然 js 的动态性可以在实现过程中用 if 去判断

都行吧，此处无论是js还其它语言都会有一个`if`判断，无非js是检测方法是否存在，其它语言可能是`xx instance of IXxxx`判断接口

> 这块我没有理解是什么意思？如果不是自动注入的话， property 本身好像没有太大问题？有 setMethod 就调用 setMothod，没的话就正常赋值。

我更希望我的配置是简单的，仅仅声明“一个叫`foo`的属性注入某个实例”，而这个属性是用`set foo`还是`setFoo`实现的，由IoC帮我自动检查掉

> onGetComponent会使用返回的组件配置进行后续操作，这块解决不了吗？

如果你的设计里是一开始找不到已经注册的`ComponentConfig`，也同样会调用插件的这个方法，只是第3个参数是`null`的话，可以解决问题

**Comment by Exodia** [comment]
> 我更希望我的配置是简单的，仅仅声明“一个叫foo的属性注入某个实例”，而这个属性是用set foo还是setFoo实现的，由IoC帮我自动检查掉

能举个例子? 比如下面的：

```javascript

var config = {
   a: {
       creator: function () { this.setB = v => this._b = v; },
       property: {
           b: 1
      }
    }
};
```

这里目前就是已经会调用a.setB(1)去注入了

**Comment by otakustay** [comment]
我已经不记得当前实现如何了，我的意思是这个配置，如果有`setB`则调用`setB`，没有则找`set b`，再没有则找普通的`b`属性，这个逻辑已经有的话就没问题了

**Comment by Exodia** [comment]
> 这个逻辑已经有的话就没问题了

目前是有 setMethod 优先使用，没有的话直接 this.prop = xxx; 这里自然会调用 set ，所以看来是 ok :)
