### ISSUE TITLE
aop 配置语法支持

### ISSUE THREAD

**Issue by Exodia** [ecomfe/uioc#46]
目前设计的配置语法如下：

```javascript
let iocConfig = {
    components: {
        myComponent: {
            creator() {
                this.doSomething = function () {};
                this.doSomething1 = function () {};
            },
            // aop 配置
            aopConfig: {
                // 通知器
                advisors: [
                    {
                        // 字符串匹配
                        matcher: 'doSomething',
                        // 具体通知
                        advices: {
                            // doSomething 执行前执行 log.start 方法
                            before: 'log.start',
                            // doSomething 执行完执行 log.end 方法
                            afterReturning: 'log.end'
                        }
                    },
                    {
                        matcher: 'doSomething1',
                        advices: {
                            before: (...args) => console.log(args)
                        }
                    },
                    {
                        matcher: /doSomething/,
                        advices: {
                            after: () => console.log('after doSomething')
                        }
                    }
                ]
            }
        }
    },
    log: {
        creator() {
            return {
                start: () => console.log(Date.now()),
                end: () => console.log(Date.now())
            }
        }
    }
};

// 打印 start end after doSomething
ioc.getComponent('myComponent').then(myComponent => myComponent.doSomething());
```

**Comment by otakustay** [comment]
1. 为啥不是整合在同一个配置下，而需要单独的`aopConfig`
2. `advice`的配置是否会有需要单独定义并多处`import`的场景，我能想到的是"配置统一的log切面，多个组件公用"
3. 从上一点来考虑，我觉得很有可能出现"所有组件都需要某个切面"这样的情况，这在各种监控需求里会发生，是否有必要支持

**Comment by Exodia** [comment]
> 为啥不是整合在同一个配置下，而需要单独的aopConfig

是说在 componentConfig 下吧？ 我一开始考虑的是这个，后面拆出来了主要是参考了spring，现在想想放在 component 下可能更合适，能够充分利用现有的接口动态添加配置。

> advice的配置是否会有需要单独定义并多处import的场景，我能想到的是"配置统一的log切面，多个组件公用"

我暂时不打算做这个支持，以后看场景添加，针对当前迫切需要的复用场景，可以考虑独立一个切面配置模块，然后多个模块使用这个。


> 从上一点来考虑，我觉得很有可能出现"所有组件都需要某个切面"这样的情况，这在各种监控需求里会发生，是否有必要支持

这块我想目前 ioc 的核心插件暂时不考虑，这种需求场景可以继承 ioc 默认加上，或者业务方再写一个插件定制化支持。

**Comment by otakustay** [comment]
另外我觉得没什么必要支持字符串格式的advice配置，倒是`$ref`是有需要的，毕竟advice就可以是一个component

**Comment by Exodia** [comment]
> 另外我觉得没什么必要支持字符串格式的advice配置，倒是$ref是有需要的，毕竟advice就可以是一个component

用$ref的话写配置较为麻烦： before: {$ref: 'log', method: 'start'}

**Comment by otakustay** [comment]
为啥不是`logStart`和`logEnd`两个component呢，函数本身就是component很合理

**Comment by Exodia** [comment]
> 为啥不是logStart和logEnd两个component呢，函数本身就是component很合理

这个前提是拦截器是无状态的，但大部分情况下，是需要保持内部状态的。另一个就是这样会导致要大量注册 aop 的 component

**Comment by otakustay** [comment]
理解了，但是为何我们在AOP这里才会有`method`这个概念，以前ioc各种场景却从来没用到过……

**Comment by Exodia** [comment]
因为 aop 是针对 method 做拦截的，而 ioc 只考虑到对象这个级别，所以 ioc 里可以没有 method 这个概念，但 aop 要做的话必然要有 method 的概念

**Comment by Exodia** [comment]
字符串形式的 advice 表达暂时先不支持, 主要原因是觉得在 js 针对切面的依赖反转似乎没太必要，在 java 里没法直接通过模块/Class引用方法去表达拦截器，在 js 里则没这个障碍：object.xxxMethod。另外本身这块也是写在配置文件中，而配置文件本身也是跟着项目的，不大存在需要依赖替换的场景。
